logging:
  full_output_frequency: 20
  name: cim_or
  out_dir: ./_experiments/all_methods
model:
  name: MLTModel
  parameters:
    mi_values:
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    protocols:
    - OR
    seed_budgets:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 15
    - 20
    - 25
    - 30
    ss_method:
      name: cim
      parameters: {}
networks:
- aucs
- ckm_physicians
- er1
- er2
- er3
- er5
- eu_trans_1
- eu_transportation
- lazega
- sf1
- sf2
- sf3
- sf5
ranking_path: _experiments/all_methods/cim_and
run:
  max_epochs_num: 1000
  patience: 1
  random_seed: null
  repetitions: 1
